In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("Global Dataset of Inflation.csv", encoding="latin1")

In [6]:
df.head()

,Country Code,IMF Country Code,Country,Indicator Type,Series Name,1970,1971,1972,1973,1974,...,2019,2020,2021,2022,Note,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63
0,ABW,314.0,Aruba,Inflation,Headline Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,4.26,1.22,0.74,6.04,Annual average inflation,NaN,NaN,NaN,NaN,NaN
1,AFG,512.0,Afghanistan,Inflation,Headline Consumer Price Inflation,25.51,25.51,-12.52,-10.68,10.23,...,2.30,5.44,5.06,NaN,Annual average inflation,NaN,NaN,NaN,NaN,NaN
2,AGO,614.0,Angola,Inflation,Headline Consumer Price Inflation,7.97,5.78,15.80,15.67,27.42,...,17.08,21.02,23.85,21.35,Annual average inflation,NaN,NaN,NaN,NaN,NaN
3,ALB,914.0,Albania,Inflation,Headline Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,1.41,1.62,2.04,6.73,Annual average inflation,NaN,NaN,NaN,NaN,NaN
4,ARE,466.0,United Arab Emirates,Inflation,Headline Consumer Price Inflation,21.98,21.98,21.98,21.98,21.98,...,-1.93,-2.08,0.18,5.22,Annual average inflation,NaN,NaN,NaN,NaN,NaN

# Data Cleaning

## Handling Missing Values

In [8]:
df.isnull().sum().sum()

np.int64(15221)

In [10]:
df = df.dropna(axis=1, how="all")

In [13]:
df.head(5)

,Country Code,IMF Country Code,Country,Indicator Type,Series Name,1970,1971,1972,1973,1974,...,2015,2016,2017,2018,2019,2020,2021,2022,Note,Unnamed: 59
0,ABW,314.0,Aruba,Inflation,Headline Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,0.48,-0.89,-0.47,3.58,4.26,1.22,0.74,6.04,Annual average inflation,NaN
1,AFG,512.0,Afghanistan,Inflation,Headline Consumer Price Inflation,25.51,25.51,-12.52,-10.68,10.23,...,-0.66,4.38,4.98,0.63,2.30,5.44,5.06,NaN,Annual average inflation,NaN
2,AGO,614.0,Angola,Inflation,Headline Consumer Price Inflation,7.97,5.78,15.80,15.67,27.42,...,9.16,32.38,29.84,19.63,17.08,21.02,23.85,21.35,Annual average inflation,NaN
3,ALB,914.0,Albania,Inflation,Headline Consumer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,1.91,1.29,1.99,2.03,1.41,1.62,2.04,6.73,Annual average inflation,NaN
4,ARE,466.0,United Arab Emirates,Inflation,Headline Consumer Price Inflation,21.98,21.98,21.98,21.98,21.98,...,4.07,1.62,1.97,3.06,-1.93,-2.08,0.18,5.22,Annual average inflation,NaN

In [12]:
df.isnull().sum().sum()

np.int64(12089)

In [14]:
df.tail(20)

,Country Code,IMF Country Code,Country,Indicator Type,Series Name,1970,1971,1972,1973,1974,...,2015,2016,2017,2018,2019,2020,2021,2022,Note,Unnamed: 59
763,SVK,936.0,Slovakia,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,-2.89,-3.98,2.43,2.52,1.91,-1.52,6.80,29.48,"Producer Price Index, All Commodities",NaN
764,SVN,961.0,Slovenia,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,-0.22,-1.36,2.15,2.07,0.68,-0.24,5.54,19.10,"Producer Price Index, All Commodities",NaN
765,SWE,144.0,Sweden,Inflation,Producer Price Inflation,NaN,NaN,4.55,11.30,24.78,...,0.01,-0.92,5.20,6.60,2.97,-0.25,10.69,22.15,"Producer Price Index, All Commodities",NaN
766,THA,578.0,Thailand,Inflation,Producer Price Inflation,-0.46,0.25,7.84,22.92,28.86,...,-4.11,-1.18,0.70,0.38,-0.96,-1.60,4.72,10.90,"Producer Price Index, All Commodities",NaN
767,TJK,923.0,Tajikistan,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,4.32,6.71,9.32,2.18,1.79,5.45,3.83,15.21,"Producer Price Index, All Commodities",NaN
768,TTO,369.0,Trinidad and Tobago,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,2.38,1.18,1.93,NaN,NaN,NaN,NaN,NaN,"Producer Price Index, All Commodities",NaN
769,TUN,744.0,Tunisia,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,5.05,1.41,4.60,7.94,5.98,1.86,9.27,10.78,"Producer Price Index, All Commodities",NaN
770,TUR,186.0,Turkey,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,5.28,4.30,15.82,27.01,17.56,12.14,43.86,130.85,"Producer Price Index, All Commodities",NaN
771,TWN,528.0,"Taiwan, China",Inflation,Producer Price Inflation,2.71,0.02,4.47,22.84,40.58,...,-8.85,-2.98,0.90,3.63,-2.26,-7.79,NaN,10.94,"Producer Price Index, All Commodities",NaN
772,TZA,738.0,"Tanzania, United Rep.",Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,3.01,6.86,1.26,6.18,7.24,NaN,NaN,NaN,"Producer Price Index, All Commodities",NaN
773,UGA,746.0,Uganda,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-1.73,-2.54,3.18,13.15,17.98,"Producer Price Index, All Commodities",NaN
774,UKR,926.0,Ukraine,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,35.69,20.92,26.45,17.58,4.14,-1.88,40.82,61.05,"Producer Price Index, All Commodities",NaN
775,URY,298.0,Uruguay,Inflation,Producer Price Inflation,13.41,21.18,89.84,114.35,79.02,...,6.83,3.35,1.67,9.67,12.78,10.46,14.42,14.19,"Producer Price Index, All Commodities",NaN
776,USA,111.0,United States,Inflation,Producer Price Inflation,3.61,3.33,4.41,13.14,18.81,...,-0.87,0.42,2.33,2.90,1.69,-2.12,8.95,7.91,"Producer Price Index, All Commodities",NaN
777,UZB,927.0,Uzbekistan,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,NaN,16.29,17.42,31.70,43.35,14.80,9.32,16.34,"Producer Price Index, All Commodities",NaN
778,VEN,299.0,"Venezuela, RB",Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,142.03,291.62,905.66,169201.78,NaN,NaN,NaN,NaN,"Producer Price Index, All Commodities",NaN
779,VNM,582.0,Vietnam,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,-0.59,-0.61,NaN,NaN,NaN,NaN,NaN,NaN,"Producer Price Index, All Commodities",NaN
780,XKX,967.0,Kosovo,Inflation,Producer Price Inflation,NaN,NaN,NaN,NaN,NaN,...,2.66,-0.07,0.59,1.35,0.93,-0.58,4.92,NaN,"Producer Price Index, All Commodities",NaN
781,ZAF,199.0,South Africa,Inflation,Producer Price Inflation,NaN,5.00,6.35,12.44,18.58,...,3.61,7.08,4.88,5.45,4.62,2.49,7.12,14.36,"Producer Price Index, All Commodities",NaN
782,ZMB,754.0,Zambia,Inflation,Producer Price Inflation,14.29,0.00,4.17,12.00,10.71,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Producer Price Index, All Commodities",NaN

In [15]:
year_cols = df.columns[5:]

df["missing_pct"] = df[year_cols].isna().mean(axis=1) * 100

df[["Country", "missing_pct"]].sort_values("missing_pct", ascending=False)

          Country  missing_pct
648       Somalia    98.181818
199          Niue    98.181818
196    Martinique    98.181818
645  Sierra Leone    98.181818
647    San Marino    98.181818
..            ...          ...
141        Poland     1.818182
476    Luxembourg     1.818182
474       Lesotho     1.818182
472     St. Lucia     1.818182
391      Bulgaria     1.818182

[783 rows x 2 columns]

In [16]:
df = df[df["missing_pct"] <= 30].copy()

In [18]:
year_cols = df.columns[5:]

df[year_cols] = df[year_cols].apply(pd.to_numeric, errors='coerce')

In [19]:
df[year_cols] = df[year_cols].interpolate(
    axis=1,
    limit=2,
    limit_area="inside"
)

In [20]:
df.isnull().sum().sum()

np.int64(740)

## Handling Duplicate Values

In [21]:
df.duplicated().sum()

np.int64(0)

## Finishing up

In [22]:
year_cols = df.columns[5:]

print(df[year_cols].min().min())
print(df[year_cols].max().max())

-72.73
94802.37

In [24]:
xyear_cols = df.columns[5:]

# Find maximum value
max_val = df[year_cols].max().max()
print("Maximum inflation:", max_val)

# Find where it occurs
for col in year_cols:
    rows = df[df[col] == max_val]
    if not rows.empty:
        print(rows[['Country', col]])

Maximum inflation: 94802.37
           Country      2018
365  Venezuela, RB  94802.37

In [25]:
min_val = df[year_cols].min().min()
print("Minimum inflation:", min_val)

for col in year_cols:
    rows = df[df[col] == min_val]
    if not rows.empty:
        print(rows[['Country', col]])

Minimum inflation: -72.73
      Country   2007
192  Zimbabwe -72.73

In [29]:
df.to_csv("Global_Dataset_of_Inflation_Cleaned.csv", index=False)

In [30]:
import os
print(os.getcwd())

/Users/avcan_009/Desktop/Cleaned_datasets/PROJECT_Datasets